### ISSUE TITLE
helper library for common UI building operations

### ISSUE THREAD

**Issue by will-hanlen** [urbit/shrub#105]
- common pith and path operations
- unpacking kids from axal

**Comment by will-hanlen** [comment]
helper which makes Sail compatible urls without the developer needing to specify the full url.

(en-tape:mastlibs %task-ui (welp here.bowl /2))

first argument is the 'viewmodel'
second argument is the here to open

**Comment by lonhep-tamfeb** [comment]
PR #121 closing this issue

**Comment by hanfel-dovned** [comment]
Solved by #121
