### ISSUE TITLE
Fix up the DM demo

### ISSUE THREAD

**Issue by will-hanlen** [urbit/shrub#11]
there is a branch called `dm` with semi-finished work.

**Comment by will-hanlen** [comment]
current state:

- works, but UI still flashes messages as from ~zod because bowl in incorrect

other than that, works.

but we probably want to move to a different architecture:

- aggregator
- publisher
- subscriber.

**Comment by hanfel-dovned** [comment]
Gonna close this one since it's a bit redundant with #14
