### ISSUE TITLE
Sky improvements

### ISSUE THREAD

**Issue by will-hanlen** [urbit/shrub#12]
* [x] editable path bar 
* [x] remove X button on hawks
* [x] UF logo in top left
* [ ] buttons: copy url/path of hawk
* [x] don't use ascii letters as a labels for a buttons
* [x] clean up borders (better distinction btwn menu and pannels)
* [x] use less monospace (except `@ps` and code)
* [ ] automatically add `value` mirroring to textarea and input

**Comment by hanfel-dovned** [comment]
Needs #20

**Comment by tiller-tolbus** [comment]
- [ ] pane close icon changes to minimize button
- [ ] build metadata goes into file view
- [ ] file view shows shrub state if it exists
- [ ] replace fas with @p in breadcrumb trail
- [ ] make path bar editable in file view
- [ ] intersperse gar between filenames in breadcrumb trail
- [ ] stretch goal: clicking gar shows %y view

**Comment by hanfel-dovned** [comment]
@will-hanlen I think this is complete and merged?

**Comment by will-hanlen** [comment]
yeah, for the most part. but some of it regressed with the sky rectification. i'll close this one and make a new issue for "revamp sky"
