### ISSUE TITLE
accel improvements

### ISSUE THREAD

**Issue by will-hanlen** [urbit/shrub#16]
- [x] ability to add multiple dependencies
- [ ] ability to specify the care of your dependencies
- [x] more than 4 cells
- [x] make all children in ++init of %accel
- [x] add a refresher (so that UI updates on non-user events)
- [x] better DevX on vase handling when `ref` points to an accel-cel
  -  gate that unvases as a type

**Comment by hanfel-dovned** [comment]
- [ ] Use %y scries, roll through kids, and slop them all together with pith->cord as a face.
- [x] Size variable in grid state, resize pokes.
- [x] Give your cell a target, and if output is a `made`, route output to target
- [ ] Wacky CSS, "accel should be weird"
- [x] Gif of all this with remote ships

**Comment by tiller-tolbus** [comment]
>  Wacky CSS, "accel should be weird"

How weird are we talking?

**Comment by tiller-tolbus** [comment]
>  ability to specify the care of your dependencies

Shouldn't we just assume %z care?

**Comment by hanfel-dovned** [comment]
> How weird are we talking?

You tell me, I was quoting you haha. But this isn't really an immediate to-do item either way, just a note for future reference.

**Comment by tiller-tolbus** [comment]
Assume a chat has a set of kids reducible to `(map @da message)`

What we begin with in the system interface is still a `(map pith pail)`

Overlay namespace /enface-message/pith/to/message takes the `(map pith pail)` from kids and runtime-level casts it to a `(map @da message)`. Overlay namespace will check the `+kids` arm of the imp of the shrub it's pointed to, to make sure `+kids` is specified as only having piths and pails of the aforementioned structure.

**Comment by hanfel-dovned** [comment]
Superseded by #30
