### ISSUE TITLE
imp/home

### ISSUE THREAD

**Issue by will-hanlen** [urbit/shrub#18]
user-configurable interface which lives at /home

this stores and displays:
- [x] all of the apps (top-level shrubs) that the user has "installed" (for now all are pre-installed)
  - maybe let the user re-order them like in %landscape
- [ ] bookmarks to local paths

**Comment by tiller-tolbus** [comment]
- [x] From `/home`, a form exists in which the user can choose from the available shrubs and install them at a path within `/home/user/`
