### ISSUE TITLE
Shrub docs

### ISSUE THREAD

**Issue by tiller-tolbus** [urbit/shrub#29]
Docs will be rendered inside the Sail editor and editable, but no further integration needed than this. 

* Trent finishes up chat/DMs; if work is done, start documenting
* Yun continues work on tasks; ^^^
* third example: diary

Step 1: lightning back-end tutorial for diary, tasks, chat
Step 2: lightning front-end tutorial for ^^^

**Comment by hanfel-dovned** [comment]
- counter with very introductory explanations (and maybe comments)

**Comment by hanfel-dovned** [comment]
**Counter**
- [x] Backend
- [x] Backend Docs
- [x] Frontend
- [x] Frontend Docs

**Diary**
- [x] Backend
- [x] Backend Docs
- [x] Frontend
- [x] Frontend Docs

**Tasks**
- [x] Backend
- [x] Backend Docs
- [x] Frontend
- [x] Frontend Docs

**Messenger**
- [x] Backend
- [x] Backend Docs
- [x] Frontend
- [x] Frontend Docs

**Comment by hanfel-dovned** [comment]
After completing all of the above, we'll merge in their individual branches, and then write a `docs` "app" for the UX. Will keep the docs in the `fil` directory for now, and we can always pull them wherever they need to go if the UX implementation requires it.
