### ISSUE TITLE
`/<` fails on a fresh build

### ISSUE THREAD

**Issue by will-hanlen** [urbit/shrub#36]
This code fails if I `|nuke` then `|start`

```hoon
/<  node
::
:: ...
::
=/  mul
  %-  mule
  |.((node [poke-stud body]))
::
:: ...
::
```

with

```
-need.%~
-have.[?([mark=@tas ship=@p desk=@tas] @tas) ^#3.[g=[n=?(@tas [@tas @tas]) a=it([n=?(@tas [@tas @tas]) v=""])] c=it(#3)]]
```

but the same code works fine if I stub it out, `|nuke`, `|start`, then replace the stub with that code.

I assume the problem is that the `node` protocol has not yet been built by the build system, so when it gets to that line, there is a type mismatch.

**Comment by will-hanlen** [comment]
https://github.com/urbit/shrub/blob/wh/sky-post-pokes/pkg/arvo/neo/cod/std/src/imp/hawk-eyre-handler.hoon#L287

**Comment by liam-fitzgerald** [comment]
pushed the change to your branch
