### ISSUE TITLE
Deploy docs via docs tile

### ISSUE THREAD

**Issue by hanfel-dovned** [urbit/shrub#43]
Right now the counter tutorial has verbage around the external Shrubbery Gall agent filesystem structure (imp/pro/con/fil etc) and alludes to working on a fakeship. We'll likely want to remove this in favor of some other flow that either allows developers to modify code within Sky, or that doesn't put any emphasis on code modification at all. 

All of our docs are in the `fil` directory as `.md` files right now. What does deploying them look like? Where do the docs exist in Sky, and what is their interface?

**Comment by hanfel-dovned** [comment]
Desired experience is an icon called Docs on the hompage. Click on it, you get all the docs we've written divided by chapter. Click on those, you get the md file (alongside the Sail editor that lets you see the udon).

So: modify imp/home to make these docs. Use imp/file to contain them.

**Comment by tiller-tolbus** [comment]
This is finished
