### ISSUE TITLE
%jinx hint

### ISSUE THREAD

**Issue by hanfel-dovned** [urbit/shrub#50]
In accel, the sail editor, and maybe some other places, users can input arbitrary Hoon. We would like to have the %jinx hint here so that they don't get their ships into infinite loops.

**Comment by tiller-tolbus** [comment]
awaiting https://github.com/urbit/UIPs/pull/62

**Comment by bonbud-macryg** [comment]
Awaiting [urbit/vere/pull/648](https://github.com/urbit/vere/pull/648)

**Comment by hanfel-dovned** [comment]
Once this is merged, we'll implement it in the appropriate spots.
