### ISSUE TITLE
docs: counter example does exist on ships, yet the docs say it does not

### ISSUE THREAD

**Issue by jalehman** [urbit/shrub#66]
> This chapter is the only real “tutorial” in that Counter doesn't currently exist on your ship. You can build Counter yourself following along this guide. The remaining three chapters will discuss shrubs that already exists in your %neo desk: Diary, Messenger, and Tasks.

Should probably remove it @bonbud-macryg @YunPearce ?

**Comment by bonbud-macryg** [comment]
Done.
