### ISSUE TITLE
tree: full crud

### ISSUE THREAD

**Issue by tiller-tolbus** [urbit/shrub#73]
Within Tree, or the "raw view" of Sky, a user should be able to perform any CRUD (create, read, update, delete) operation through a generic interface. 

- [x] Create: User can make a new node of any available type with a state vase input as a text-input noun and a set of dependencies as an expandable text input of `@tas` - `pith`. 
(note: without service discovery, "available types" are just a listing of the files in `our/cod/out/imp`
- [x] Read: Pretty-prints the state of a node as user-readable data
- [x] Update: All studs in the `+poke` arm of the node have a corresponding textbox and "Poke" button. Textbox attempts to render input text as a noun. The stud corresponding to the poke is implicit and does not need to be input by the user. 
- [ ] Delete: %tomb the current node and all children (two clicks: user must confirm deletion)

**Comment by lonhep-tamfeb** [comment]
full CRUD in tree achieved
To complete best %tomb experience, waiting for %ack response in neo to be finished.
