### ISSUE TITLE
messenger: test various cases

### ISSUE THREAD

**Issue by tiller-tolbus** [urbit/shrub#75]
We haven't tested messenger at all on the live network and in very few kinds of cases on fakeships. 

Try using messenger in various intermediate states on the live network and on fakeships, including cases where neo is installed on one ship and not another. See if messenger can catch up when neo is installed after a message is already pending. Document results inside this issue and we will update the issue to handle whatever bugs are found. 

We are sure based on some user feedback that messenger has some bugs, so we just need to figure out the extent of them, diagnose, and fix them.

**Comment by bonbud-macryg** [comment]
Can't create a DM chat between two fakeships.

Dojo output on sender ~fun:
```
>>> %new-dm
>>  %messenger-diff
neo: bad deal: /~fun/home/messenger/dms/~bud
poke-ack
gall: raw-poke fail :neo %neo-raw-poke
```

Dojo output on receiver ~bud:
```
clay: read-at-tako fail [desk=%neo care=%b case=[%da p=~2024.6.28..12.05.46..9b5a] path=/neo-raw-poke]
clay: no files match /mar/neo-raw-poke/hoon
[%error-building-mark %neo-raw-poke]
[%error-building-dais %neo-raw-poke]
```

**Comment by hanfel-dovned** [comment]
I found ~winter-paches's talk on the importance of unit testing to be very convincing.

**Comment by tiller-tolbus** [comment]
Per @liam-fitzgerald this seems like a core problem with Shrubbery networking that needs to be addressed, would assume that cross-network actions will generally fail until this is fixed. Putting this issue on waiting until it's resolved

**Comment by tiller-tolbus** [comment]
New release fixes shrub networking, please retry @bonbud-macryg

**Comment by bonbud-macryg** [comment]
Works between fake galaxies, comets, and live planets.

When I create a DM with a ship that isn't a peer yet I get this in the Dojo.

```
>>> %new-dm
>>  %messenger-diff
; ~mex is your neighbor
[%missing-deli [i=[%p ~mex] t=[i=%home t=~[%messenger %dms [%p ~tex] %pub]]]]
[%lost-moor ship=~mex pith=[i=%home t=[i=%messenger t=~[%dms [%p ~tex] %pub]]]]
[%nothing [i=[%p ~mex] t=[i=%home t=[i=%messenger t=[i=%dms t=[i=[%p ~tex] t=[i=%pub ~]]]]]]]
[ %nothing
  [ i=[%p ~mex]
      t
    [ i=%home
      t=[i=%messenger t=[i=%dms t=[i=[%p ~tex] t=[i=%pub t=[i=[%da ~2024.7.11..13.54.52] ~]]]]]
    ]
  ]
]
[%fresh [i=[%p ~mex] t=[i=%home t=[i=%messenger t=[i=%dms t=[i=[%p ~tex] t=[i=%pub ~]]]]]]]
[ %missing-deli
  [i=[%p ~mex] t=[i=%home t=~[%messenger %dms [%p ~tex] %pub [%da ~2024.7.11..13.54.52]]]]
]
```

When I create a new DM with a ship I am peers with I get this in the Dojo.

```
>>> %new-dm
>>  %messenger-diff
>>  %dm-diff
>>> 'got dm diff'
```

**Comment by liam-fitzgerald** [comment]
Ugh this is an upstream issue I think ffs, will investigate later today.

**Comment by bonbud-macryg** [comment]
Still getting some terminal noise here on a branch rebased to include latest `develop` changes.

`%new-dm` and `%dm-diff` stuff is all expected logging from sigpams.

## First message between two fakeships
### Sender
```
>>> %new-dm
>>  %messenger-diff
[%missing-deli [i=[%p ~bud] t=[i=%home t=~[%messenger %dms [%p ~fun] %pub]]]]
[%lost-moor ship=~bud pith=[i=%home t=[i=%messenger t=~[%dms [%p ~fun] %pub]]]]
[%nothing [i=[%p ~bud] t=[i=%home t=[i=%messenger t=[i=%dms t=[i=[%p ~fun] t=[i=%pub ~]]]]]]]
```

### Receiver
```
>>  %dm-diff
>>> 'got dm diff'
[%missing-deli [i=[%p ~fun] t=[i=%home t=~[%messenger %dms [%p ~bud] %pub]]]]
[%lost-moor ship=~fun pith=[i=%home t=[i=%messenger t=~[%dms [%p ~bud] %pub]]]]
[%nothing [i=[%p ~fun] t=[i=%home t=[i=%messenger t=[i=%dms t=[i=[%p ~bud] t=[i=%pub ~]]]]]]]
[%nothing [i=[%p ~fun] t=[i=%home t=[i=%messenger t=[i=%dms t=[i=[%p ~bud] t=[i=%pub t=[i=[%da ~2024.7.31..09.48.01] ~]]]]]]]]
[%fresh [i=[%p ~fun] t=[i=%home t=[i=%messenger t=[i=%dms t=[i=[%p ~bud] t=[i=%pub ~]]]]]]]
[%missing-deli [i=[%p ~fun] t=[i=%home t=~[%messenger %dms [%p ~bud] %pub [%da ~2024.7.31..09.48.01]]]]]
```

## Subsequent messages between two fakeships
### Receiver
```
[%nothing [i=[%p ~fun] t=[i=%home t=[i=%messenger t=[i=%dms t=[i=[%p ~bud] t=[i=%pub t=[i=[%da ~2024.7.31..09.42.30] ~]]]]]]]]
[%fresh [i=[%p ~fun] t=[i=%home t=[i=%messenger t=[i=%dms t=[i=[%p ~bud] t=[i=%pub ~]]]]]]]
[%missing-deli [i=[%p ~fun] t=[i=%home t=~[%messenger %dms [%p ~bud] %pub [%da ~2024.7.31..09.42.30]]]]]
```

No noise on the sender's terminal.

**Comment by hanfel-dovned** [comment]
Replaced by #126 and #128.
