### ISSUE TITLE
Sky: Overlays in Nav

### ISSUE THREAD

**Issue by tiller-tolbus** [urbit/shrub#90]
Overlay namespaces are a good way to view the same data in different ways. 

One example use-case of this is an overlay that shows comments on arbitrary pieces of data, that can be toggled on or off. 

This issue is waiting for the 8/5 deadline for overlays and virtual shrubs per the core roadmap. In the meantime, some discussion should be had about what other desired features we want here.

**Comment by will-hanlen** [comment]
https://migrev-dolseg.com/scratch/view/url-is-strategy-plus-pith

**Comment by will-hanlen** [comment]
we have thrown out the idea of treating overlays as an argument to the framework along with the argument of what viewmodel to render with

**Comment by hanfel-dovned** [comment]
We'll use the `blue` overlay renderer for this in conjunction with the overlay path box.
