### ISSUE TITLE
Tree: Prep for Sky integration

### ISSUE THREAD

**Issue by tiller-tolbus** [urbit/shrub#97]
- [x] Tree should be one column with all of the CRUD options available only to the current node
- [x] Children are listed as clickable links that load into new webpages (see: current Sky raw view)
- [x] To reach feature parity with Sky, Tree should display clickable links to the Hoon files representing state type of current node

Following this, we can begin integration with Sky that involves ensuring that CSS can be injected into Tree from Sky Settings, and that navbar behaviors still work within Tree

**Comment by will-hanlen** [comment]
i think this is done
